### ISSUE TITLE
[Wotlk] Quest: Totem of Tikti [#9540]

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#143] opened 2015-11-10 19:18 UTC
When starting the quest Totem of Tikti right after an other player starts it (within 1-5seconds) you'r quest will not spawn an NPC furlborg. You will not receive the slowfall buff, not until you disband and re-obtain the quest.

Quest:
http://www.wowhead.com/quest=9540/totem-of-tikti

**Comment by Argonn** [comment] 2015-11-10 19:19
Also applies to Totem of Yor.

Quest:
http://www.wowhead.com/quest=9541/totem-of-yor

**Comment by Argonn** [comment] 2015-11-10 19:21
Also applies to Totem of Vark

Quest:
http://www.wowhead.com/quest=9542/totem-of-vark

**Comment by Grz3s** [comment] 2015-11-10 19:27
interesting.... let me check whats wrong with it...

**Comment by Grz3s** [comment] 2015-11-10 23:27
ok this is a serious problem....
Looks like that... while quest start/end script is "in progres" ... noone else can activate it again...
before ill do anything about it (probably it will be core issue anyway) ... i need to look on blizz... to make sure how it should work.

**Comment by offl** [comment] 2015-11-10 23:36
I tested it on retail - after I abbandon quest and tried to start it again, NPC doesn't appear. But if quest is started by different player, NPC spawned.
After logout this problem is solved.
So, I guess it's a blizzlike sustem, that preventing multiple summoning by one player.

**Comment by Argonn** [comment] 2015-11-11 09:28
I can agree with offl if this is the way it works on retail, its not directly a not-blizzlike-bug. But still it feels buggy and maybe it should have been fixed on retail as well. If its not that much of a deal (low prio) I think it shouldn't be left out for fixing. It can mess-up your questing while in a party (which I always do).

But again, its not for me to decide,

**Comment by Grz3s** [comment] 2015-11-11 19:14
pls dont forget we talking about ..WOTLK... what we have currently is few years younger upgraded version.  It may work different ...than before.
From my experience...
- i know that sometimes .. npcFlags (quest and gossip) are removed from main npc... while start/end script is loaded....so other players have to wait... until flags a back to default..
- also.. once i wanted to record.. quest with thrall arriving nagrand (long nice event)... but becouse someone else did that quest before, and thrall was siting next to questgiver. (thrall has terrible despawn time there ~15 - 20mins)... I finished quest and event didnt start for me... so i lost 1 and only chence to have it :)....
these are only examples ...but i know that strange things happen there also... and main problem here we have.. we wont fix'em like we would like to... we have to try, to do the same, what was there ;)
--
BTW:
i checked this quest on blizz yesterday.. and i can confirm ... once u take this quest... npc will spawn.. but after abandon and take it again... spawn doesnt work... For me even log off/on ... didnt help. so yes ...i can confirm that...
Also i'll wait tonight ... and let someone else take it... and ill do the same stright after him... we'll see what will happen :)

**Comment by offl** [comment] 2015-11-11 19:43
>i know that sometimes .. npcFlags (quest and gossip) are removed from main npc... while start/end script is loaded....so other players have to wait... until flags a back to default..
also.. once i wanted to record.. quest with thrall arriving nagrand (long nice event)... but becouse someone else did that quest before, and thrall was siting next to questgiver. (thrall has terrible despawn time there ~15 - 20mins)... I finished quest and event didnt start for me... so i lost 1 and only chence to have it :).... these are only examples ...but i know that strange things happen there also... and main problem here we have.. we wont fix'em like we would like to... we have to try, to do the same, what was there ;) --

Yes, incredible standard mechanic with adding\removing flags.

>BTW:
i checked this quest on blizz yesterday.. and i can confirm ... once u take this quest... npc will spawn.. but after abandon and take it again... spawn doesnt work... 

Guess these comments([comment](http://www.wowhead.com/quest=9540/totem-of-tikti#comments:id=213834), [comment](http://www.wowhead.com/quest=9542/totem-of-vark#comments:id=67737)) can confirm this too.
So, if this mechanic was 8 years ago, why two events cannot be activated in same time by different players?

Maybe these quest-starters have more specific scripts on retail.

**Comment by Grz3s** [comment] 2015-12-06 23:47
hi again...
I lost on this problem few* days... thinking how i can make it better* ....
Well ... 
```quote
Maybe these quest-starters have more specific scripts on retail.
```
On retail quest starts from spell casted by player - s.30426 (server-side spell)

```code
Opcode: SMSG_SPELL_EXECUTE_LOG
[0] Caster GUID: Full: 0x5000000039B0F00 Type: Player Low: 60493568 Name: Draej
[0] Spell ID: 30426 (30426)
[0] Count: 1
[0] [0] Spell Effect: Summon (28)
[0] [0] Count: 1
[0] [0] [0] Summoned GUID: Full: 0xF13043E30002E778 Type: Creature Entry: 17379 Low: 190328
```
Its not a problem to create this spell.... and issue (new script wont load until prev finish) will be fixed.
But this will create even worse problem.
I wont be able to *force* summoned creature to (face/cast spells etc on player) ...
I tried everything:
all target flags... - non of them targets player
i tried with EAI action - 45   ACTION_T_THROW_AI_EVENT -- wanted to throw this event by player... so summoned could respond... but this thing works only with creatures...
It looks like will leave it as it is now... 

If someeone wants to look at that second problem ... 
theres new script...(only for tests)
```sql
-- missing spell added
DELETE FROM spell_template WHERE id = 30426;
INSERT INTO spell_template (id, attr, attr_ex, attr_ex2, attr_ex3, proc_flags, proc_chance, duration_index, effect0, effect0_implicit_target_a, effect0_implicit_target_b, effect0_radius_idx, effect0_apply_aura_name, effect0_misc_value, effect0_misc_value_b, effect0_trigger_spell, comments) VALUES
(30426, 256, 0, 0, 0, 0, 101, 40, 28, 43, 0, 15, 0, 17379, 64, 0, 'Stillpine Ancestor Akida');

-- q.9539 'Totem of Coo'
DELETE FROM dbscripts_on_quest_start WHERE id = 9539;
INSERT INTO dbscripts_on_quest_start (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(9539,0,15,30426,0,0,0,6,0,0,0,0,0,0,0,0,''); -- with spell
-- (9539,0,10,17379,120000,0,0,0,0,0,0,0,-4178.3,-12515.1,44.3627,2.63132,'summon Stillpine Ancestor Akida');  -- with DB_scripts -- better option
UPDATE quest_template SET StartScript = 9539 WHERE entry = 9539;

-- Stillpine Ancestor Akida
UPDATE creature_template SET SpeedRun = 1, MovementType = 2 WHERE Entry = 17379; -- maypoints will be set by script
DELETE FROM creature_movement_template WHERE entry = 17379;
INSERT INTO creature_movement_template (entry, point, position_x, position_y, position_z, waittime, script_id, orientation, model1, model2) VALUES
(17379, 1, -4178.3,-12515.1,44.3627, 8000, 1737901, 100, 0, 0),
(17379, 2, -4156.91,-12516.1,45.0017, 0, 0,6.12162, 0, 0),
(17379, 3, -4134.95,-12516.6,44.8959, 0, 0,6.27084, 0, 0),
(17379, 4, -4123.49,-12517.2,44.8246, 0, 0,6.00223, 0, 0),
(17379, 5, -4097.6,-12522.4,42.0019, 0, 0,6.03915, 0, 0),
(17379, 6, -4077.12,-12530.6,43.7753, 0, 0,5.85851, 0, 0),
(17379, 7, -4060.63,-12538.1,44.1549, 0, 0,5.66217, 0, 0),
(17379, 8, -4050.65,-12546.2,42.2335, 0, 0,5.59541, 0, 0),
(17379, 9, -4034.49,-12560.5,44.9926, 0, 0,5.52865, 0, 0),
(17379, 10, -4016.73,-12579.5,49.464, 0, 0,5.45011, 0, 0),
(17379, 11, -4003.06,-12595.4,53.3469, 0, 0,5.41477, 0, 0),
(17379, 12, -3989.72,-12611.6,59.1497, 0, 0,5.39514, 0, 0),
(17379, 13, -3970.6,-12636.3,64.4018, 0, 0,5.35979, 0, 0),
(17379, 14, -3959.1,-12651.6,71.234, 0, 0,5.35587, 0, 0),
(17379, 15, -3945.98,-12669.7,75.8562, 0, 0,5.32838, 0, 0),
(17379, 16, -3937.34,-12685.6,81.0235, 0, 0,5.18701, 0, 0),
(17379, 17, -3925.95,-12719,89.6782, 0, 0,5.06135, 0, 0),
(17379, 18, -3915.914,-12743.41,98.69524, 15000, 1737902,100, 0, 0);

DELETE FROM dbscripts_on_creature_movement WHERE id IN (1737901);
INSERT INTO dbscripts_on_creature_movement (id, delay, command, datalong, datalong2, buddy_entry, search_radius, data_flags, dataint, dataint2, dataint3, dataint4, x, y, z, o, comments) VALUES
(1737901,1,21,1,0,0,0,0,0,0,0,0,0,0,0,0,'active'),
(1737901,4,36,0,0,0,0,0x02,0,0,0,0,0,0,0,0,'face player'), -- problem here ... how to target player????
(1737901,5,0,0,0,0,0,0,2000000666,0,0,0,0,0,0,0,''),
(1737901,6,25,1,0,0,0,0,0,0,0,0,0,0,0,0,'RUN ON');

-- ServerToClient: SMSG_COMBAT_LOG_MULTIPLE (0x33A8) Length: 45 ConnIdx: 0 Time: 02/11/2011 14:52:29.000 Number: 7606
-- Count: 1
-- [0] Unknown: 0
-- Opcode: SMSG_SPELL_EXECUTE_LOG
-- [0] Caster GUID: Full: 0x5000000039B0F00 Type: Player Low: 60493568 Name: Draej
-- [0] Spell ID: 30426 (30426)
-- [0] Count: 1
-- [0] [0] Spell Effect: Summon (28)
-- [0] [0] Count: 1
-- [0] [0] [0] Summoned GUID: Full: 0xF13043E30002E778 Type: Creature Entry: 17379 Low: 190328

-- ServerToClient: SMSG_CHAT (0x61E4) Length: 87 ConnIdx: 0 Time: 02/11/2011 14:52:33.000 Number: 7650
-- Type: MonsterEmote (16)
-- Language: Universal (0)
-- GUID: Full: 0xF13043E30002E778 Type: Creature Entry: 17379 Low: 190328
-- Constant time: 0
-- Name Length: 25
-- Name: Stillpine Ancestor Akida
-- Receiver GUID: Full: 0x5000000039B0F00 Type: Player Low: 60493568 Name: Draej
-- Text Length: 28
-- Text: %s urges you to follow him.
-- Chat Tag: 32 (32)
```

**Closed** 2021-03-17 20:30 UTC
Labels: Quest
