### ISSUE TITLE
Scarlet Cannon 28833

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#79] opened 2015-06-22 18:23 UTC
Scarlet Cannon cannot move on BlizzServer
Only  turn up and down left and right

**Comment by Grz3s** [comment] 2015-06-22 19:14
this is difficult one: 
probably core issue with vehicle system:
more can be found here im sure:
https://github.com/TrinityCore/TrinityCore/pull/13642

**Comment by xfurry** [comment] 2015-06-23 09:58
The problem is that we don't have any clue on which vehicles to not allow movement.
I need to research this, but eventually we might need to add some CREATURE_FLAG_EXTRA_...

**Comment by Grz3s** [comment] 2015-09-12 14:18
this may solve this problem?
https://github.com/pete318/TrinityCore/commit/30b3ec53052a9892933c5f4defa5e018eb173ff7

**Comment by Tauriella** [comment] 2015-09-13 20:17
No
Trinity have the same Bug

**Comment by Rushor** [comment] 2015-09-15 18:47
well tc didn't merged this yet, the pr fixes the issue

**Comment by Grz3s** [comment] 2016-03-06 13:24
it looks like TC has solved this problem already:
https://github.com/TrinityCore/TrinityCore/commit/cdb16c5181b0ad02e5dd3a4afa44151fb119b62e

**Comment by xfurry** [comment] 2016-04-24 21:23
Trinity fix looks promising.
However I need to do some more research before I push this.
It turns out that the flag they used isn't valid for all rooted vehicles (maybe there are many flags) and also I need to adjust the code to our vehicle implementation

**Closed** 2016-04-25 22:18 UTC
Labels: Core / ScriptDev2
