### ISSUE TITLE
Missing Stratholme Teleporter

### ISSUE THREAD

**Issue by Tauriella** [unified-db/Database#26] opened 2015-02-11 13:50 UTC
Missing exit Teleporter from Stratholme
Map 329
GroundZ 132,468750
FloorZ 119,659317
X 3928,597656
Y -3374,333496
Z 119,659317

**Comment by Grz3s** [comment] 2015-02-15 22:55
need more info... screenshot ..avi etc..

**Comment by Tauriella** [comment] 2015-02-16 00:59
I have testet on a BlizzServer 
You don't can out for this Area
Sorry for my mistake

**Comment by Rushor** [comment] 2015-02-16 01:28
which area? you mean the entrance at the maingate? probably post a screenshot for this :)

**Comment by Tauriella** [comment] 2015-02-16 13:45
![stratholme](https://cloud.githubusercontent.com/assets/10637389/6212892/6978237e-b5ea-11e4-98f2-0bb6dd7cf364.jpg)

**Comment by Dainara82** [comment] 2015-02-18 06:50
Yes this is normal, but in the dungeon it Takes an Second exit an backdoor you can enter it from outside only with the key, so if you have the key, you can go in and out when ever you want but only from the backdoor (Second exit near the ostwalldoor) the key drops by Magistrate-Barthilas-10435

**Comment by xfurry** [comment] 2015-02-18 09:56
Well, there are many dungeons that are missing the exit teleporter implementation.

A few other examples would be: TK - Botanica, TK - Mechanar, Ahn'kahet, Azjol'Nerub
Maybe there are others, but these are the ones that I know that are missing the area_trigger_teleport on instance exit (after last boss).

**Comment by evil-at-wow** [comment] 2015-02-20 20:30
Note that Stratholme has been split in two separate parts these days, so what you see on live today is not what it used to be in WoTLK or earlier. I'm not entirely sure, but the screenshot actually makes me think this is what was intended or rumored to be an entry to Naxx. It was never accessible for players, and it certainly wasn't an easy exit from the Slaughterhouse area.

Unrelated FYI for @xfurry / @Grz3s: the TK exit teleporters have been fixed in TBC-DB. If I recall correctly, 1.4.1 has the fixed instance portals and 1.4.2 has the missing areatrigger_teleport data.

**Comment by cala** [comment] 2015-03-03 08:47
@evil-at-wow is right.
I confirm with an 100% confidence that this portal/areatrigger was previously expected to be the entrance to Naxxramas raid dungeon (the original Classic and TBC version of it) and confirmed as such by Blizzard.

They wanted something similar to the relation between Blackrock Depths => Molten Core or Blackrock Spire => Blackwing Lair with players having to run to the instance once or twice to get attunement to the raid dungeon, while the raid dungeon was still accessible through the instance for players without attunement.

@Grz3s you can safely close this issue.
This was latter changed for Naxxaramas to a 100% attunement requirement before the raid instance was released. Thus, this portal was never used nor removed.

**Comment by xfurry** [comment] 2015-03-03 09:07
Don't close this yet. We still have this part to solve:

> A few other examples would be: TK - Botanica, TK - Mechanar, Ahn'kahet, Azjol'Nerub
> Maybe there are others, but these are the ones that I know that are missing the area_trigger_teleport on instance exit (after last boss).

**Comment by Tobschinski** [comment] 2015-06-20 14:27
Just in case someone is curious what is behind: https://youtu.be/m1esdGySyQs?t=816

**Comment by Grz3s** [comment] 2021-02-19 21:18
fixed with `instance_files_system`
![xxxx](https://user-images.githubusercontent.com/2374069/108562595-0407ad80-72f8-11eb-9a59-fa7045c3b15d.jpg)

**Closed by Grz3s** 2021-02-19 21:18 UTC
