### ISSUE TITLE
[Wotlk] NPC: Tunneler [#16968] 

### ISSUE THREAD

**Issue by Argonn** [unified-db/Database#124] opened 2015-09-28 07:19 UTC
When the NPC is sub-merged, it will not attack you. You will go in/out of combat within a second. And so you can just walk over it without starting a fight.

However when you attack a Tunneler from range, it will merge out of the ground and attack you like it would normally. 
But when you attack it when standing in melee range. It will bug out (being invisible) until killed.

NPC:
http://www.wowhead.com/npc=16968/tunneler

**Comment by Grz3s** [comment] 2015-09-28 22:01
pls check this and let me know what u think?
```sql
-- Tunneler
Delete from `creature_ai_scripts` where `creature_id`= 16968;
Insert into `creature_ai_scripts` values
('1696801','16968','11','0','100','0','0','0','0','0','19','33554432','0','0','0','0','0','0','0','0','0','0','Tunneler - Remove Unselectable Unit Flag on Spawn'),
('1696802','16968','11','0','100','0','0','0','0','0','11','29147','0','16','11','33928','0','0','21','0','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on Spawn'),
('1696804','16968','4','0','100','0','0','0','0','0','28','0','29147','0','28','0','33928','0','22','1','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Set Phase 1 on Aggro'),
('1696805','16968','9','5','100','1','50','100','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Hai\'shulud - Start Combat Movement at 50 Yards (Phase 1)'),
('1696806','16968','9','5','100','1','5','50','500','500','21','0','0','0','0','0','0','0','0','0','0','0','Hai\'shulud - Prevent Combat Movement between 5 and 50 Yards (Phase 1)'),
('1696807','16968','9','5','100','1','0','5','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Hai\'shulud - Start Combat Movement Below 5 Yards (Phase 1)'),
('1696808','16968','9','5','100','1','0','50','2100','4500','11','31747','1','0','0','0','0','0','0','0','0','0','Tunneler - Cast Poison (Phase 1)'),
('1696809','16968','0','5','100','1','20400','20400','45000','50000','11','32738','1','0','0','0','0','0','0','0','0','0','Tunneler - Cast Bore (Phase 1)'),
('1696810','16968','2','0','100','1','30','0','12000','17000','11','32714','0','1','0','0','0','0','0','0','0','0','Tunneler - Cast Enrage at 30% HP'),
('1696811','16968','0','5','100','1','3000','3000','10000','10000','28','0','29147','0','28','0','33928','0','0','0','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive (Phase 1)'),
('1696812','16968','9','5','100','0','50','100','0','0','11','29147','0','16','11','33928','0','0','22','2','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Set Phase 2 at 50 Yards (Phase 1)'),
('1696813','16968','9','3','100','1','0','5','500','500','22','1','0','0','0','0','0','0','0','0','0','0','Tunneler - Set Phase 1 at 5 Yards (Phase 2)'),
('1696814','16968','9','3','100','1','0','8','500','500','28','0','29147','0','28','0','33928','0','21','0','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Prevent Combat Movement at 5 Yards (Phase 2)'),
('1696815','16968','7','0','100','0','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Tunneler - Set Phase 0 on Evade'),
('1696816','16968','21','0','100','0','0','0','0','0','11','29147','0','21','11','33928','0','0','21','0','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on REACHED_HOME');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '16968';
```

**Comment by Grz3s** [comment] 2015-09-28 22:33
```quote
(...)You will go in/out of combat within a second(...)
```
What ability gives you to do that??? (not using gm mode on off?)
anyway
pls try this - without any not player commands.
```sql
-- Tunneler
Delete from `creature_ai_scripts` where `creature_id`= 16968;
Insert into `creature_ai_scripts` values
('1696801','16968','11','0','100','0','0','0','0','0','19','33554432','0','0','0','0','0','0','0','0','0','0','Tunneler - Remove Unselectable Unit Flag on Spawn'),
('1696802','16968','11','0','100','0','0','0','0','0','11','29147','0','16','11','33928','0','0','21','0','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on Spawn'),
('1696804','16968','4','0','100','0','0','0','0','0','28','0','29147','0','28','0','33928','0','22','1','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Set Phase 1 on Aggro'),
('1696805','16968','9','5','100','1','50','100','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Hai\'shulud - Start Combat Movement at 50 Yards (Phase 1)'),
('1696806','16968','9','5','100','1','5','50','500','500','21','0','0','0','0','0','0','0','0','0','0','0','Hai\'shulud - Prevent Combat Movement between 5 and 50 Yards (Phase 1)'),
('1696807','16968','9','5','100','1','0','5','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Hai\'shulud - Start Combat Movement Below 5 Yards (Phase 1)'),
('1696808','16968','9','5','100','1','0','50','2100','4500','11','31747','1','0','0','0','0','0','0','0','0','0','Tunneler - Cast Poison (Phase 1)'),
('1696809','16968','9','5','100','1','0','5','25000','27000','11','32738','1','1','0','0','0','0','0','0','0','0','Tunneler - Cast Bore (Phase 1)'),
('1696810','16968','2','0','100','1','30','0','12000','17000','11','32714','0','1','0','0','0','0','0','0','0','0','Tunneler - Cast Enrage at 30% HP'),
('1696811','16968','0','5','100','1','3000','3000','10000','10000','28','0','29147','0','28','0','33928','0','0','0','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive (Phase 1)'),
('1696812','16968','9','5','100','0','50','100','0','0','11','29147','0','16','11','33928','0','0','22','2','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Set Phase 2 at 50 Yards (Phase 1)'),
('1696813','16968','9','3','100','1','0','5','500','500','22','1','0','0','0','0','0','0','0','0','0','0','Tunneler - Set Phase 1 at 5 Yards (Phase 2)'),
('1696814','16968','9','3','100','1','0','8','500','500','28','0','29147','0','28','0','33928','0','21','0','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Prevent Combat Movement at 5 Yards (Phase 2)'),
('1696815','16968','7','0','100','0','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Tunneler - Set Phase 0 on Evade'),
('1696816','16968','21','0','100','0','0','0','0','0','11','29147','0','21','11','33928','0','0','21','0','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on REACHED_HOME');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '22038';
```

**Comment by Argonn** [comment] 2015-09-29 06:56
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '22038';
Zero rows updated. 

UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '16857';
Zero rows updated.

**Comment by Grz3s** [comment] 2015-09-29 12:47
hmm... this fix is not added yet... ..i wanted you to test it :)
did you copy this code and checked it?

**Comment by Argonn** [comment] 2015-09-29 12:48
Yes i did a direct sql delete/update/insert. And than a .reload all

**Comment by Grz3s** [comment] 2015-09-29 12:50
i tried this many Times.... and only it happened ..when i use gm on/off .... or killed it by command  and respawn in 1 secs ....but this is not what normal player can do...
tell me how to reproduce that problem step by step/.

**Comment by Argonn** [comment] 2015-09-29 12:59
Movie coming up..

**Comment by Grz3s** [comment] 2015-09-29 13:17
ok :)

**Comment by Grz3s** [comment] 2015-09-29 17:03
difficult task:
pls check this one:
```sql
-- Tunneler
Delete from `creature_ai_scripts` where `creature_id`= 16968;
Insert into `creature_ai_scripts` values
('1696801','16968','11','0','100','0','0','0','0','0','11','29147','0','16','11','33928','0','0','21','0','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on Spawn'),
('1696802','16968','4','0','100','0','0','0','0','0','28','0','29147','0','28','0','33928','0','22','1','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Set Phase 1 on Aggro'),
('1696803','16968','9','5','100','1','0','50','500','500','21','0','0','0','0','0','0','0','0','0','0','0','Tunneler - Prevent Combat Movement between 0 and 50 Yards (Phase 1)'),
('1696804','16968','9','5','100','1','50','100','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Tunneler - Start Combat Movement at 50 Yards (Phase 1)'),
('1696805','16968','0','5','100','1','1000','1000','5000','5000','28','0','29147','0','28','0','33928','0','0','0','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive (Phase 1)'),
('1696806','16968','9','5','100','1','0','50','2100','4500','11','31747','1','0','0','0','0','0','0','0','0','0','Tunneler - Cast Poison (Phase 1)'),
('1696807','16968','9','5','100','1','0','5','25000','27000','11','32738','1','1','0','0','0','0','0','0','0','0','Tunneler - Cast Bore (Phase 1)'),
('1696808','16968','2','0','100','1','30','0','12000','17000','11','32714','0','1','0','0','0','0','0','0','0','0','Tunneler - Cast Enrage at 30% HP'),
('1696809','16968','7','0','100','0','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Tunneler - Set Phase 0 on Evade'),
('1696810','16968','21','0','100','0','0','0','0','0','11','29147','0','21','11','33928','0','0','21','0','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on REACHED_HOME');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '16968';

-- Marauding Crust Burster
Delete from `creature_ai_scripts` where `creature_id`= 16857;
Insert into `creature_ai_scripts` values
('1685701','16857','11','0','100','0','0','0','0','0','11','29147','0','16','11','33928','0','0','21','0','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on Spawn'),
('1685702','16857','4','0','100','0','0','0','0','0','28','0','29147','0','28','0','33928','0','22','1','0','0','Marauding Crust Burster - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Set Phase 1 on Aggro'),
('1685703','16857','9','5','100','1','0','50','500','500','21','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Prevent Combat Movement between 0 and 50 Yards (Phase 1)'),
('1685704','16857','9','5','100','1','50','100','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Start Combat Movement at 50 Yards (Phase 1)'),
('1685705','16857','0','5','100','1','1000','1000','10000','10000','28','0','29147','0','28','0','33928','0','0','0','0','0','Marauding Crust Burster - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive (Phase 1)'),
('1685706','16857','9','5','100','1','0','50','2100','4500','11','31747','1','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Cast Poison (Phase 1)'),
('1685707','16857','7','0','100','0','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Set Phase 0 on Evade'),
('1685708','16857','21','0','100','0','0','0','0','0','11','29147','0','21','11','33928','0','0','21','0','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on REACHED_HOME');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '16857';

-- correct UnitFlag
UPDATE creature_template SET UnitFlags = 0, ExtraFlags = 0 WHERE entry = 16968;
UPDATE creature_template SET UnitFlags = 0, ExtraFlags = 0 WHERE entry = 16857;
DELETE FROM creature_addon WHERE guid IN (SELECT guid FROM creature WHERE id = 16968);
DELETE FROM creature_addon WHERE guid IN (SELECT guid FROM creature WHERE id = 16857);
DELETE FROM creature_template_addon WHERE entry IN (16968,16857);
INSERT INTO creature_template_addon (entry, mount, bytes1, b2_0_sheath, b2_1_pvp_state, emote, moveflags, auras) VALUES 
(16968, 0, 0, 1, 1, 0, 0, NULL),
(16857, 0, 0, 1, 1, 0, 0, NULL);
```
let me know of result ofc ;)

**Comment by Argonn** [comment] 2015-09-30 08:02
Turned out the first update kinda wrecked our server. So will update the last SQL when we bring the server down asap.

**Comment by Argonn** [comment] 2015-09-30 09:58
It appears to be closer already, but the devil is in the details in this case:
1. He comes out of the ground, with light-speed. On retail he had a short animation.
2. When leaving combat again, he stays above ground.
3. When going out of range (NOT SIGHT) of the range attack, he will follow you above ground.

Will test these details vs retail.

**Comment by BeerfishWoW** [comment] 2015-09-30 10:00
As soon as you go out of range of the Tunneleren, he should submerge again and move toward the player underground. Using the code above, the Tunneler moves to the player while above ground, which is not the way it should be. Furthermore, upon loosing aggro with the PC, the Tunneler should submerge. With the code pasted above, that doesn't happen either. See this video of how I think the Tunneler should behave: https://youtu.be/M7q3f2CE2Rc?t=1m18s.

**Comment by Grz3s** [comment] 2015-09-30 21:42
Hi and thanks for replay... Sql i gave you before was only to check ... if creature aggro player in correct way.
Please note that this is not "retail" and it will never be 100% the same... we can only 'can' do what core allow us to do.
Anyway ..pls look at complete sql... and let me know what u think about this one:
```sql
-- Tunneler
Delete from `creature_ai_scripts` where `creature_id`= 16968;
Insert into `creature_ai_scripts` values
('1696801','16968','11','0','100','0','0','0','0','0','11','29147','0','16','11','33928','0','0','21','0','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on Spawn'),
('1696802','16968','4','0','100','0','0','0','0','0','28','0','29147','0','28','0','33928','0','22','1','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Set Phase 1 on Aggro'),
('1696803','16968','0','5','100','1','2000','2000','5000','5000','28','0','29147','0','28','0','33928','0','0','0','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive (Phase 1)'),
('1696804','16968','9','5','100','1','5','40','2100','4500','11','31747','1','0','0','0','0','0','0','0','0','0','Tunneler - Cast Poison (Phase 1)'),
('1696805','16968','9','5','100','1','0','5','25000','27000','11','32738','1','1','0','0','0','0','0','0','0','0','Tunneler - Cast Bore (Phase 1)'),
('1696806','16968','2','0','100','1','30','0','12000','17000','11','32714','0','1','0','0','0','0','0','0','0','0','Tunneler - Cast Enrage at 30% HP'),
('1696807','16968','9','5','100','1','0','2','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Tunneler - Start Combat Movement Below 2 Yards (Phase 1)'),
('1696808','16968','9','5','100','1','2','40','500','500','21','0','0','0','0','0','0','0','0','0','0','0','Tunneler - Prevent Combat Movement between 2 and 40 Yards (Phase 1)'),
('1696809','16968','9','5','100','1','50','100','500','500','11','29147','0','16','11','33928','0','0','22','2','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Set Phase 2 at 50 Yards (Phase 1)'),
('1696810','16968','9','3','100','1','40','90','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Tunneler - Start Combat Movement at 40 Yards (Phase 2)'),
('1696811','16968','9','3','100','1','0','10','500','500','22','1','0','0','0','0','0','0','0','0','0','0','Tunneler - Set Phase 1 at 10 Yards (Phase 2)'),
('1696812','16968','7','0','100','0','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Tunneler - Set Phase 0 on Evade'),
('1696813','16968','7','0','100','0','0','0','0','0','11','29147','0','16','11','33928','0','0','21','0','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on Evade'),
('1696814','16968','1','0','100','1','500','500','1000','1000','11','29147','0','48','11','33928','0','0','21','0','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on OOC');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '16968';

-- Marauding Crust Burster
Delete from `creature_ai_scripts` where `creature_id`= 16857;
Insert into `creature_ai_scripts` values
('1685701','16857','11','0','100','0','0','0','0','0','11','29147','0','16','11','33928','0','0','21','0','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on Spawn'),
('1685702','16857','4','0','100','0','0','0','0','0','28','0','29147','0','28','0','33928','0','22','1','0','0','Marauding Crust Burster - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Set Phase 1 on Aggro'),
('1685703','16857','0','5','100','1','2000','2000','5000','5000','28','0','29147','0','28','0','33928','0','0','0','0','0','Marauding Crust Burster - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive (Phase 1)'),
('1685704','16857','9','5','100','1','5','40','2100','4500','11','31747','1','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Cast Poison (Phase 1)'),
('1685705','16857','9','5','100','1','0','2','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Start Combat Movement Below 2 Yards (Phase 1)'),
('1685706','16857','9','5','100','1','2','40','500','500','21','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Prevent Combat Movement between 2 and 40 Yards (Phase 1)'),
('1685707','16857','9','5','100','1','50','100','500','500','11','29147','0','16','11','33928','0','0','22','2','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Set Phase 2 at 50 Yards (Phase 1)'),
('1685708','16857','9','3','100','1','40','90','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Start Combat Movement at 40 Yards (Phase 2)'),
('1685709','16857','9','3','100','1','0','10','500','500','22','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Set Phase 1 at 10 Yards (Phase 2)'),
('1685710','16857','7','0','100','0','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster- Set Phase 0 on Evade'),
('1685711','16857','7','0','100','0','0','0','0','0','11','29147','0','16','11','33928','0','0','21','0','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on Evade'),
('1685712','16857','1','0','100','1','500','500','1000','1000','11','29147','0','48','11','33928','0','0','21','0','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Prevent Combat Movement on OOC');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '16857';

-- correct UnitFlag
UPDATE creature_template SET UnitFlags = 0, ExtraFlags = 0 WHERE entry = 16968;
UPDATE creature_template SET UnitFlags = 0, ExtraFlags = 0 WHERE entry = 16857;
DELETE FROM creature_addon WHERE guid IN (SELECT guid FROM creature WHERE id = 16968);
DELETE FROM creature_addon WHERE guid IN (SELECT guid FROM creature WHERE id = 16857);
DELETE FROM creature_template_addon WHERE entry IN (16968,16857);
INSERT INTO creature_template_addon (entry, mount, bytes1, b2_0_sheath, b2_1_pvp_state, emote, moveflags, auras) VALUES 
(16968, 0, 0, 1, 1, 0, 0, NULL),
(16857, 0, 0, 1, 1, 0, 0, NULL);
```

Few notes before comment:
- core makes all creature not taking any aggro in first 5 secs after spawn....
- I tried everything ... to make him ... submerge on evade... (all way back to spawn point he just wont listen to any command - no idea why -- but it looks like evade mehanic works in that way). He will submerge after reahed home.

**Comment by Grz3s** [comment] 2015-10-03 13:38
These creatures a pain in the ....
Look at tchem again

Fixed:  (bore passive) -- overtakes aggro sometimes ..and as a effect we'll see tchem comming out and then bore again

```sql
-- Tunneler
Delete from `creature_ai_scripts` where `creature_id`= 16968;
Insert into `creature_ai_scripts` values
('1696801','16968','11','0','100','0','0','0','0','0','21','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Prevent Combat Movement on Spawn'),
('1696802','16968','1','0','100','1','50','500','3000','3000','11','29148','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual on OOC'),
('1696803','16968','4','0','100','0','0','0','0','0','28','0','29147','0','28','0','33928','0','22','1','0','0','Marauding Crust Burster - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Set Phase 1 on Aggro'),
('1696804','16968','0','5','100','1','0','50','5000','5000','28','0','29147','0','28','0','33928','0','0','0','0','0','Marauding Crust Burster - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive (Phase 1)'),
('1696805','16968','9','5','100','1','5','40','2100','4500','11','31747','1','0','0','0','0','0','0','0','0','0','Tunneler - Cast Poison (Phase 1)'),
('1696806','16968','9','5','100','1','0','5','25000','27000','11','32738','1','1','0','0','0','0','0','0','0','0','Tunneler - Cast Bore (Phase 1)'),
('1696807','16968','2','0','100','1','30','0','12000','17000','11','32714','0','1','0','0','0','0','0','0','0','0','Tunneler - Cast Enrage at 30% HP'),
('1696808','16968','9','5','100','1','0','2','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Start Combat Movement Below 2 Yards (Phase 1)'),
('1696809','16968','9','5','100','1','2','40','500','500','21','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Prevent Combat Movement between 2 and 40 Yards (Phase 1)'),
('1696810','16968','9','5','100','1','50','100','500','500','11','29147','0','16','11','33928','0','0','22','2','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Set Phase 2 at 40 Yards (Phase 1)'),
('1696811','16968','9','3','100','1','40','90','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Start Combat Movement at 40 Yards (Phase 2)'),
('1696812','16968','9','3','100','1','0','10','500','500','22','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Set Phase 1 at 10 Yards (Phase 2)'),
('1696813','16968','7','0','100','0','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Set Phase 0 on Evade');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '16968';

-- Marauding Crust Burster
Delete from `creature_ai_scripts` where `creature_id`= 16857;
Insert into `creature_ai_scripts` values
('1685701','16857','11','0','100','0','0','0','0','0','21','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Prevent Combat Movement on Spawn'),
('1685702','16857','1','0','100','1','50','500','3000','3000','11','29148','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual on OOC'),
('1685703','16857','4','0','100','0','0','0','0','0','28','0','29147','0','28','0','33928','0','22','1','0','0','Marauding Crust Burster - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Set Phase 1 on Aggro'),
('1685704','16857','0','5','100','1','0','50','5000','5000','28','0','29147','0','28','0','33928','0','0','0','0','0','Marauding Crust Burster - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive (Phase 1)'),
('1685705','16857','9','5','100','1','5','40','2100','4500','11','31747','1','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Cast Poison (Phase 1)'),
('1685706','16857','9','5','100','1','0','2','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Start Combat Movement Below 2 Yards (Phase 1)'),
('1685707','16857','9','5','100','1','2','40','500','500','21','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Prevent Combat Movement between 2 and 40 Yards (Phase 1)'),
('1685708','16857','9','5','100','1','50','100','500','500','11','29147','0','16','11','33928','0','0','22','2','0','0','Marauding Crust Burster - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Set Phase 2 at 40 Yards (Phase 1)'),
('1685709','16857','9','3','100','1','40','90','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Start Combat Movement at 40 Yards (Phase 2)'),
('1685710','16857','9','3','100','1','0','10','500','500','22','1','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Set Phase 1 at 10 Yards (Phase 2)'),
('1685711','16857','7','0','100','0','0','0','0','0','22','0','0','0','0','0','0','0','0','0','0','0','Marauding Crust Burster - Set Phase 0 on Evade');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '16857';

-- correct UnitFlag
UPDATE creature_template SET UnitFlags = 0, ExtraFlags = 0, SpeedRUN = 1.19048 WHERE entry = 16968;
UPDATE creature_template SET UnitFlags = 0, ExtraFlags = 0, SpeedRUN = 1.19048 WHERE entry = 16857;
DELETE FROM creature_addon WHERE guid IN (SELECT guid FROM creature WHERE id = 16968);
DELETE FROM creature_addon WHERE guid IN (SELECT guid FROM creature WHERE id = 16857);
DELETE FROM creature_template_addon WHERE entry IN (16968,16857);
INSERT INTO creature_template_addon (entry, mount, bytes1, b2_0_sheath, b2_1_pvp_state, emote, moveflags, auras) VALUES 
(16968, 0, 0, 1, 1, 0, 0, '33928'),
(16857, 0, 0, 1, 1, 0, 0, '33928');
```

**Comment by Argonn** [comment] 2015-10-04 09:10
Will test this when the issue has been resolved around aut-kick-on-join :)

**Comment by Grz3s** [comment] 2015-10-04 11:38
have a same thing:/ ...
luckly ... had old backup... so i can keep doing smth ;)

**Comment by BeerfishWoW** [comment] 2015-10-09 09:58
We've just installed your latest fix on ApexWoW.com. Argonn will test it and post his results.

**Comment by Argonn** [comment] 2015-10-09 10:04
Looks very good! 
Only small detail, when the tuneller has followed you (UNDERGROUND!!) he will stay underground when he reaches you to re-initate the fight. When you hit the tuneller he will pop out of the ground.

So everything works good, until he reaches you when you went out of range of his spit, and he reached you again in underground mode. He will stay underground (while spitting even) until you hit him.

**Comment by BeerfishWoW** [comment] 2015-10-09 13:01
What's more, the Tunneler still pops up out of the ground way too fast. He's out in an instant, whereas he should come up slowly - as if he steadily emerges from beneath the earth.

**Comment by Grz3s** [comment] 2015-10-09 17:21
```quote
So everything works good, until he reaches you when you went out of range of his spit, and he reached you again in underground mode. He will stay underground (while spitting even) until you hit him.
```
will investigate this...

```qoute
What's more, the Tunneler still pops up out of the ground way too fast. He's out in an instant, whereas he should come up slowly as he steadily emerges from beneath the earth.
```
this cannot be solved by DB... its all spell mechanics.. how they react after removing them  from npc..etc..
belive me... i dont think its a big issue.

**Comment by al3xc1985** [comment] 2015-10-11 15:47
now i remember one more case for spells like this one. the transformation phase of buru. when he lose his case, or how ever is called, the animation is ultra fast. I am sure that spells like this one have a special mechanic and must be implemented in the right way

**Comment by Grz3s** [comment] 2015-10-11 16:47
```quote
 I am sure that spells like this one have a special mechanic and must be implemented in the right way
```
This issue need to be solved by core ppl

BTW:
I did small update for -- Tunneler (pls check and let me know results)
What should be fixed:
- shouldnt stay underground anymore (if attacked)
- player shouldnt be able to attack him while he is underground (phase 2)
FIX:
```sql
-- Tunneler
Delete from `creature_ai_scripts` where `creature_id`= 16968;
Insert into `creature_ai_scripts` values
('1696801','16968','11','0','100','0','0','0','0','0','21','0','0','0','19','33554432','0','0','0','0','0','0','Tunneler - Remove Unselectable Unit Flag and Prevent Combat Movement on Spawn'),
('1696802','16968','1','0','100','1','50','500','3000','3000','11','29148','0','0','0','0','0','0','0','0','0','0','Tunneler - Cast Sandworm Submerge Visual on OOC'),
('1696803','16968','4','0','100','0','0','0','0','0','28','0','29147','0','28','0','33928','0','22','1','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive and Set Phase 1 on Aggro'),
('1696804','16968','0','5','100','1','0','50','2000','2000','28','0','29147','0','28','0','33928','0','19','33554432','0','0','Tunneler - Remove Sandworm Submerge Visual and Remove Tunnel Bore Passive (Phase 1)'),
('1696805','16968','9','5','100','1','5','40','2100','4500','11','31747','1','0','0','0','0','0','0','0','0','0','Tunneler - Cast Poison (Phase 1)'),
('1696806','16968','9','5','100','1','0','5','25000','27000','11','32738','1','1','0','0','0','0','0','0','0','0','Tunneler - Cast Bore (Phase 1)'),
('1696807','16968','2','0','100','1','30','0','12000','17000','11','32714','0','1','0','0','0','0','0','0','0','0','Tunneler - Cast Enrage at 30% HP'),
('1696808','16968','9','5','100','1','0','2','500','500','21','1','0','0','0','0','0','0','0','0','0','0','Tunneler - Start Combat Movement Below 2 Yards (Phase 1)'),
('1696809','16968','9','5','100','1','2','40','500','500','21','0','0','0','0','0','0','0','0','0','0','0','Tunneler - Prevent Combat Movement between 2 and 40 Yards (Phase 1)'),
('1696810','16968','9','5','100','1','50','100','500','500','11','29147','0','16','11','33928','0','0','22','2','0','0','Tunneler - Cast Sandworm Submerge Visual and Cast Tunnel Bore Passive and Set Phase 2 at 40 Yards (Phase 1)'),
('1696811','16968','9','3','100','1','40','90','500','500','21','1','0','0','18','33554432','0','0','0','0','0','0','Tunneler - Start Combat Movement and Unselectable Unit Flag at 40 Yards (Phase 2)'),
('1696812','16968','9','3','100','1','0','10','500','500','22','1','0','0','0','0','0','0','0','0','0','0','Tunneler - Set Phase 1 at 10 Yards (Phase 2)'),
('1696813','16968','7','0','100','0','0','0','0','0','22','0','0','0','19','33554432','0','0','0','0','0','0','Tunneler - Set Phase 0 on Evade');
UPDATE creature_template SET AIName='EventAI' WHERE `entry` = '16968';
```

**Comment by al3xc1985** [comment] 2015-10-11 18:06
hey, i was thinking of why don't you create a milestone?

poke @stfx about custom animation

**Comment by Argonn** [comment] 2015-10-12 06:53
I would like to thank @Grz3s for his last fix. This works like a wonder.
1. When moving out of spit-range. He goes undergroed and follows you around.
2. When coming close, he always comes out of the ground.
3. When underground he is no longer targetable.
4. When you move out of combat range (reset) he will move in his current state (above or underground) back to his position. When aboveground he will go back underground when the location has been reached.

Epic work guys!

**Comment by xfurry** [comment] 2015-10-12 21:38
So, which version is the good one?
For the spawn animation, I think we need to use some spell visual or emote. Something like: http://www.wowhead.com/spell=26262/birth

**Comment by Grz3s** [comment] 2015-10-12 22:44
hey @xfurry i'll make complete script for all simmilar type creatures...
so we can add it at once...

**Comment by Argonn** [comment] 2015-10-13 09:30
"So, which version is the good one?
For the spawn animation, I think we need to use some spell visual or emote. Something like: http://www.wowhead.com/spell=26262/birth"

The last code block is what we have tested. And showed me the best results.

**Closed** 2015-10-17 12:46 UTC

**Comment by al3xc1985** [comment] 2015-10-17 20:07
how about the animation speed

**Comment by Grz3s** [comment] 2015-10-17 20:53
animation is core issue.. so pls report it there

**Comment by xfurry** [comment] 2015-10-17 22:48
> how about the animation speed?

I'll look into this
